# Generated by Django 5.0 on 2024-01-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_id', models.IntegerField(unique=True)),
                ('officer_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('officer_mobile', models.IntegerField()),
                ('officer_name', models.CharField(max_length=255)),
                ('officer_station', models.CharField(max_length=255)),
            ],
        ),
    ]
