# Generated by Django 5.0 on 2024-01-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epolice_django', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
