# Generated by Django 5.0 on 2024-01-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epolice_django', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
