# Generated by Django 5.0 on 2024-01-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epolice_django', '0013_complaints'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
