# Generated by Django 5.0 on 2024-01-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epolice_django', '0021_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='user_email',
        ),
        migrations.DeleteModel(
            name='Citizen',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
