# Generated by Django 5.0 on 2024-01-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Epolice_django', '0025_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaints',
        ),
    ]
